services:
  # Backend API service
  - type: web
    name: secure-file-share-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 24h
      - key: FILE_UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 50000000
      - key: ALLOWED_FILE_TYPES
        value: jpg,jpeg,png,gif,pdf,doc,docx,txt,zip,rar,xlsx,pptx
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: FRONTEND_URL
        value: https://secure-file-share.onrender.com
